config/routes.rb
Rails.application.routes.draw do
  

  

  root 'home#index'
  get 'home/index', to: 'home#index'

  #Headers
  get 'headers/gradient'
  get 'headers/solidcolor'
  get 'headers/parallax'
  get 'headers/typing'
  get 'headers/backgroundimage'

  #Pages
  get 'pages/About'
  get 'pages/Portfolio'
  get 'pages/PortfolioDetails'
  get 'pages/Blog'
  get 'pages/BlogDetails'
  get 'pages/BlogGrid'
  get 'pages/Testmonial'
  get 'pages/Gallery'
  get 'pages/Team'
  get 'pages/Client'
  get 'pages/Form'
  get 'pages/Footers'
  get 'pages/Tabs'
  get 'pages/Accordion'
  get 'pages/Progressbar'
  get 'pages/Countdown'
  get  'pages/Buttons'
  get  'pages/ListStyle'
  get  'pages/Feature'
  get 'pages/Login'
  get 'pages/Register'
  get 'pages/CommingSoon'
  get 'pages/Contact'
  get 'pages/error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController
  def gradient
  end

  def solidcolor
  end

  def parallax
  end

  def typing
  end

  def backgroundimage
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def About
  end

  def Portfolio
  end

  def PortfolioDetails
  end

  def Blog
  end

  def BlogDetails
  end

  def BlogGrid
  end

  def Testmonial
  end

  def Gallery
  end

  def Team
  end

  def Client
  end

  def Form
  end

  def Footers
  end

  def Tabs
  end

  def Accordion
  end

  def Progressbar
  end

  def Countdown
  end
  
  def Buttons
  end

  def ListStyle
  end

  def Feature
  end

  def Login
    render :layout => "empty"
  end

  def Register
    render :layout => "empty"
  end

  def CommingSoon
    render :layout => "empty"
  end

  def Contact
  end

  def error
    render :layout => "empty"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/headers/backgroundimage.html.erb
<section class="u-py-100 u-h-100vh u-flex-center header-bck-img">
  <div class="container">
    <div class="row">
      <div class="col-12 u-mt-80 text-center">
        <div class="col-12 u-mt-80 text-center">
          <h1 class="display-4 u-fw-300 text-white u-mb-40">
            Grow Your Online Business with Love
          </h1>
          <p class="u-fs-22 text-white u-lh-1_8 u-mb-40">
            Engage your customers with our beautiful themes
          </p>
          <a href="#" class="btn btn btn-rounded btn-white px-md-5">
            Get Started
          </a>
        </div>
      </div>
    </div>
</section>

app/views/headers/gradient.html.erb
<section class="u-py-100 u-h-100vh u-flex-center header-gradient">
  <div class="container">
    <div class="row">
      <div class="col-12 u-mt-80 text-center">
        <h1 class="display-4 u-fw-300 text-white u-mb-40">
          Grow Your Online Business with Love
        </h1>
        <p class="u-fs-22 text-white u-lh-1_8 u-mb-40">
          Engage your customers with our beautiful themes
        </p>
        <a href="#" class="btn btn btn-rounded btn-white ml-3 px-md-5">
          Get Started
        </a>
      </div>
    </div>
  </div>
</section>

app/views/headers/parallax.html.erb
<section class="u-py-100 u-h-100vh u-flex-center parallax">
  <div class="container">
    <div class="row">
      <div class="col-12 u-mt-80 text-center">
        <h1 class="display-4 u-fw-300 text-white u-mb-40">
          Grow Your Online Business with Love
        </h1>
        <p class="u-fs-22 text-white u-lh-1_8 u-mb-40">
          Engage your customers with our beautiful themes
        </p>
        <a href="#" class="btn btn btn-rounded btn-primary ml-3 px-md-5">
          Get Started
        </a>
      </div>
    </div>
  </div>
</section>

app/views/headers/solidcolor.html.erb
<section class="u-py-100 u-h-100vh u-flex-center bg-purple">
  <div class="container">
    <div class="row">
      <div class="col-12 u-mt-80 text-center">
        <h1 class="display-4 u-fw-300 text-white u-mb-40">
          Grow Your Online Business with Love
        </h1>
        <p class="u-fs-22 text-white u-lh-1_8 u-mb-40">
          Engage your customers with our beautiful themes
        </p>
        <a href="#" class="btn btn btn-rounded btn-white px-md-5">
          Get Started
        </a>
      </div>
    </div>
  </div>
</section>

app/views/headers/typing.html.erb
<section class="u-py-100 u-h-100vh u-flex-center main-bg-gradient-1">
  <div class="container">
    <div class="row">
      <div class="col-12 u-mt-80 text-center">
        <h1 class="display-4 u-fw-500 text-white u-mb-40">
          Devdap is build for
          <span class="text-purple" data-type="App, SEO, Software"></span>
          <span class="typed-curcor text-purple">|</span>
        </h1>
        <p class="u-fs-18 text-white u-lh-1_8 u-mb-40">
          Devdap is an elegant, modern and fully customizable App Landing, SaaS Landing, WebApp, SEO Landing, Startup Landing & Product
          Landing Multi-Purpose HTML template
        </p>
        <a href="#" class="btn btn btn-rounded btn-primary m-2 px-md-5 py-3" data-scrollto="demo">
          Explore Demos
        </a>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer>
      <section class="bg-white">
            <div class="container">
                  <div class="row">
                        <div class="col-lg-4">
                              <h2>Devdap</h2>
                              <p class="u-my-40">
                                    Nam liber tempor cum soluta nobis eleifend they option congue is nihil imper per tem por legere is me velit doming vulputate.
                              </p>
                              <form class="form-inline">
                                    <div class="input-group box-shadow-v1 u-rounded-50 bg-white u-of-hidden">
                                          <div class="input-group-addon bg-white border-0 pl-3 pr-3 icon-padding pr-0">
                                                <span class="icon icon-Mail text-primary"></span>
                                          </div>
                                          <input type="text" class="form-control border-0 p-3" placeholder="Enter your email">
                                          <button type="submit" class="input-group-btn btn bg-white">
                                                <span class="icon icon-Arrow text-primary"></span>
                                          </button>
                                    </div>
                              </form>
                        </div>
                        <div class="col-lg-2 ml-auto">
                              <h4>Useful Links</h4>
                              <div class="u-h-4 u-w-50 bg-purple rounded mt-3 u-mb-40"></div>
                              <ul class="list-unstyled u-lh-2">
                                    <li>
                                          <a href="#">About Us </a>
                                    </li>
                                    <li>
                                          <a href="#">Testimonials </a>
                                    </li>
                                    <li>
                                          <a href="#">Pricing </a>
                                    </li>
                                    <li>
                                          <a href="#">Contact Us</a>
                                    </li>
                                    <li>
                                          <a href="#">News </a>
                                    </li>
                              </ul>
                        </div>
                        <div class="col-lg-3 ml-auto">
                              <h4>Contact Info</h4>
                              <div class="u-h-4 u-w-50 bg-purple rounded mt-3 u-mb-40"></div>
                              <ul class="list-unstyled">
                                    <li class="mb-2">
                                          <span class="icon icon-Phone2 text-primary mr-2"></span> 123. 456. 789
                                    </li>
                                    <li class="mb-2">
                                          <span class="icon icon-Mail text-primary mr-2"></span>
                                          <a href="blog.devdap@gmail.com">blog.devdap@gmail.com</a>
                                    </li>
                                    <li class="mb-2">
                                          <span class="icon icon-Pointer text-primary mr-2"></span> Punjab, Pakistan
                                    </li>
                              </ul>
                              <ul class="list-inline social social-rounded social-white mt-4">
                                    <li class="list-inline-item">
                                          <a href="#">
                                                <i class="fa fa-facebook"></i>
                                          </a>
                                    </li>
                                    <li class="list-inline-item">
                                          <a href="#">
                                                <i class="fa fa-twitter"></i>
                                          </a>
                                    </li>
                                    <li class="list-inline-item">
                                          <a href="#">
                                                <i class="fa fa-google-plus"></i>
                                          </a>
                                    </li>
                                    <li class="list-inline-item">
                                          <a href="#">
                                                <i class="fa fa-linkedin"></i>
                                          </a>
                                    </li>
                              </ul>
                        </div>
                  </div>
            </div>
      </section>
      <div class="container text-center p-4">
            <p class="mb-0">
                  Build with
                  <span class="icon icon-Heart text-primary mx-2"></span> love for you.
            </p>
      </div>
</footer>
<div class="scroll-top bg-white box-shadow-v1">
      <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

app/views/layouts/_navigation.html.erb
<header class="header header-shrink header-inverse fixed-top">
   <div class="container">
      <nav class="navbar navbar-expand-lg px-md-0">
         <a class="navbar-brand" href="#">
            <span class="logo-default">
               <%= link_to home_index_path do %>
               <%= content_tag :h2, "2F | ", :class => "text-white" %>
               <% end %>
            </span>    
         </a>
         <button class="navbar-toggler p-0" data-toggle="collapse" data-target="#navbarNav">
            <div class="hamburger hamburger--spin js-hamburger">
               <div class="hamburger-box">
                  <div class="hamburger-inner"></div>
               </div>
            </div>
         </button>
         <div class="collapse navbar-collapse px-md-0" id="navbarNav">
                  <%= link_to 'MON COMPTE', home_index_path, class: "nav-link" %>
            <ul class="navbar-nav ml-auto">
               <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Choisir un corps de métiers 
                  <i class="fa fa-chevron-down u-fs-12 ml-1"></i>
               </a>
               <div class="dropdown-menu box-shadow-v2" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="">Electricien</a>
                  <a class="dropdown-item" href="">Chauffagiste</a>
                  <a class="dropdown-item" href="">Plombier</a>
                  <a class="dropdown-item" href="">Serrurier</a>
               </div>
            </li>
            <li class="nav-item">
               <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Entrez votre adresse" aria-label="Search">
                  <button type=button class=btn btn-primary start id=monBouton data-loading-text=Chargement...>
                     <span><i class="material-icons">search</i></span>
                  </button>
               </form>
            </li>

         </ul>
      </div>
   </nav>
</div>
</header>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <meta name="description" content="A complete landing page solution for any business">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Beautiful landing Page solution for your business</title>
      <!-- Favicon -->
      <%= favicon_link_tag 'favicon/favicon.ico' %>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
      <!-- Menu Partials -->
      <%= render 'layouts/navigation' %>
      <%= yield %>
      <!-- Footer Partials -->
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <meta name="description" content="A complete landing page solution for any business">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Beautiful landing Page solution for your business</title>
      <!-- Favicon -->
      <%= favicon_link_tag 'favicon/favicon.ico' %>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
      <%= yield %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </body>
</html>

app/views/pages/Blog.html.erb
<section class="u-py-100 u-pt-lg-200 u-pb-lg-150 u-flex-center primary-back-color">
		<div class="container">
			<div class="row">
				<div class="col-12 text-center text-white">
					<h1 class="text-purple">
						Latest Blog Posts
					</h1>
					<div class="u-h-4 u-w-50 bg-white rounded mx-auto my-4"></div>
					<p class="lead text-purple">
						Read and get updated on how we progress.
					</p>
				</div>
			</div>
		</div>
	</section>
	<section class="py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<article class="post box-shadow-v2 bg-white">
                        <div class="post__img">
                        <%=image_tag("blog/1_1.jpg", alt: "")%>
                        
							
						</div>
						<div class="post__content">
							<div class="post__date box-shadow-v2 d-inline-block text-center px-2 px-md-4 py-2 rounded">
								<h4 class="u-fs-20 u-fs-md-36">
									<span class="text-primary"> 20</span>
									<span class="d-block u-fs-16">March 2017</span>
								</h4>
							</div>
							<div class="post__share">
								<span class="icon icon-Share bg-white box-shadow-v2 share__icon"></span>
								<div class="post__share-media">
									<a href="#">
										<i class="fa fa-facebook bg-facebook text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-twitter bg-twitter text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-google-plus bg-google text-white share__icon"></i>
									</a>
								</div>
							</div>
							<h2 class="post__title">
								The Important Standard Post Format
							</h2>
							<ul class="list-inline u-my-20">
								<li class="list-inline-item mr-3">
									<a href="#">By
										<strong>Admin</strong>
									</a>
								</li>
								<li class="list-inline-item mr-3">
									<a href="#">in
										<strong>Technology</strong>
									</a>
								</li>
								<li class="list-inline-item">
									<a href="#">8
										<strong>Comments</strong>
									</a>
								</li>
							</ul>
							<p>
								Nam liber tempor cum soluta nobis eleifend option congue is nihil imper per tem por legere me that doming vulputate velit
								esse molestie possim wisi enim ad placerat facer possim assum minim there veniam.
							</p>
							<a href="#" class="btn btn-purple u-mt-20">Read More</a>
						</div>
					</article>
					<article class="post box-shadow-v2 bg-white">
						<div class="post__img">
						<%=image_tag("blog/1_2.jpg", alt: "")%>
						</div>
						<div class="post__content">
							<div class="post__date box-shadow-v2 d-inline-block text-center px-2 px-md-4 py-2 rounded">
								<h4 class="u-fs-20 u-fs-md-36">
									<span class="text-primary"> 20</span>
									<span class="d-block u-fs-16">March 2017</span>
								</h4>
							</div>
							<div class="post__share">
								<span class="icon icon-Share bg-white box-shadow-v2 share__icon"></span>
								<div class="post__share-media">
									<a href="#">
										<i class="fa fa-facebook bg-facebook text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-twitter bg-twitter text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-google-plus bg-google text-white share__icon"></i>
									</a>
								</div>
							</div>
							<h2 class="post__title">
								The Important Standard Post Format
							</h2>
							<ul class="list-inline u-my-20">
								<li class="list-inline-item mr-3">
									<a href="#">By
										<strong>Admin</strong>
									</a>
								</li>
								<li class="list-inline-item mr-3">
									<a href="#">in
										<strong>Technology</strong>
									</a>
								</li>
								<li class="list-inline-item">
									<a href="#">8
										<strong>Comments</strong>
									</a>
								</li>
							</ul>
							<p>
								Nam liber tempor cum soluta nobis eleifend option congue is nihil imper per tem por legere me that doming vulputate velit
								esse molestie possim wisi enim ad placerat facer possim assum minim there veniam.
							</p>
							<a href="#" class="btn btn-purple u-mt-20">Read More</a>
						</div>
					</article>
					<article class="post box-shadow-v2 bg-white">
						<div class="post__img">
                        <%=image_tag("blog/1_3.jpg", alt: "")%>
						</div>
						<div class="post__content">
							<div class="post__date box-shadow-v2 d-inline-block text-center px-2 px-md-4 py-2 rounded">
								<h4 class="u-fs-20 u-fs-md-36">
									<span class="text-primary"> 20</span>
									<span class="d-block u-fs-16">March 2017</span>
								</h4>
							</div>
							<div class="post__share">
								<span class="icon icon-Share bg-white box-shadow-v2 share__icon"></span>
								<div class="post__share-media">
									<a href="#">
										<i class="fa fa-facebook bg-facebook text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-twitter bg-twitter text-white share__icon"></i>
									</a>
									<a href="#">
										<i class="fa fa-google-plus bg-google text-white share__icon"></i>
									</a>
								</div>
							</div>
							<h2 class="post__title">
								The Important Standard Post Format
							</h2>
							<ul class="list-inline u-my-20">
								<li class="list-inline-item mr-3">
									<a href="#">By
										<strong>Admin</strong>
									</a>
								</li>
								<li class="list-inline-item mr-3">
									<a href="#">in
										<strong>Technology</strong>
									</a>
								</li>
								<li class="list-inline-item">
									<a href="#">8
										<strong>Comments</strong>
									</a>
								</li>
							</ul>
							<p>
								Nam liber tempor cum soluta nobis eleifend option congue is nihil imper per tem por legere me that doming vulputate velit
								esse molestie possim wisi enim ad placerat facer possim assum minim there veniam.
							</p>
							<a href="#" class="btn btn-purple u-mt-20">Read More</a>
						</div>
					</article>
				</div>
				<aside id="sidebar" class="col-lg-4">
					<div class="widget sidebar-widget">
						<h2 class="sidebar-widget-title">Search For</h2>
						<div class="widget-content">
							<div class="input-group u-rounded-50 border u-of-hidden u-mb-20">
								<div class="input-group-addon bg-white border-0 pl-3 pr-3 icon-padding pr-0">
									<span class="icon icon-Search text-primary"></span>
								</div>
								<input type="text" class="form-control border-0 p-3" placeholder="Type & hit enter">
							</div>
						</div>
					</div>
					<div class="widget sidebar-widget">
						<h2 class="sidebar-widget-title">Categories</h2>
						<div class="widget-content">
							<ul>
								<li>
									<a href="#">Branding / Design
										<span class="badge">67</span>
									</a>
								</li>
								<li>
									<a href="#">Marketing
										<span class="badge">2</span>
									</a>
								</li>
								<li>
									<a href="#">Uncategorized
										<span class="badge">7</span>
									</a>
								</li>
								<li>
									<a href="#">Branding / Design
										<span class="badge">20</span>
									</a>
								</li>
								<li>
									<a href="#">Marketing
										<span class="badge">26</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="sidebar-widget">
						<div class="post-tabs">
							<div class="post-tab-list clearfix">
								<h2 class="sidebar-widget-title">
									<a href="#tab-1" data-tab="tab-1" class="active">recent posts</a>
								</h2>
								<h2 class="sidebar-widget-title">
									<a href="#tab-2" data-tab="tab-2" class="">popular posts</a>
								</h2>
							</div>
							<div class="widget-content">
								<div id="tab-1" class="post__tab-content active">
                                    <div class="media align-items-center mb-3">
                                    <%=image_tag("blog/1.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										
										<div class="media-body">
											<h5>
												<a href="#">The Important Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/2.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/3.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">The Important Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/1_1.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">Some words about my vacation</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
								</div>
								<div id="tab-2" class="post__tab-content">
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/2.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/3.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">The Important Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/1_1.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">Some words about my vacation</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
									<div class="media align-items-center mb-3">
                                    <%=image_tag("blog/1.jpg", class: "u-w-70 rounded-circle u-h-70 mr-3", alt: "")%>
										<div class="media-body">
											<h5>
												<a href="#">The Important Standard Post Format</a>
											</h5>
											<span class="u-fs-15">Nov 28, 2017</span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="sidebar-widget">
						<div class="tag-cloud">
							<h2 class="sidebar-widget-title">popular tags</h2>
							<div class="widget-content tags-list">
								<a href="#">Fashion</a>
								<a href="#">Audio</a>
								<a href="#">Lifestyle</a>
								<a href="#">Travel</a>
								<a href="#">Food</a>
								<a href="#">Products</a>
								<a href="#">Education</a>
								<a href="#">envato</a>
								<a href="#">UI UX</a>
								<a href="#">WordPress</a>
								<a href="#">Blogging</a>
							</div>
						</div>
					</div>
				</aside>
			</div>
		</div>
	</section>

app/views/pages/Buttons.html.erb
<section class="u-py-100 u-pt-lg-200 u-pb-lg-150 u-flex-center main-bg-gradient-1">
		<div class="container">
			<div class="row">
				<div class="col-12 text-center">
					<h1 class="text-purple">
						Buttons
					</h1>
					<div class="u-h-4 u-w-50 bg-white rounded mx-auto my-4"></div>
					<p class="text-white">
						Modern cool buttons work with both link and button tag :)
					</p>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="container">
			<div class="row">
				<div class="col-12 text-center">
					<button class="btn btn-rounded btn-primary px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-green px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-white px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-pulple-light px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-yellow px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-primary px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-green px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-white px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-pulple-light px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-yellow px-md-5 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-primary px-md-4 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-green px-md-4 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-white px-md-4 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-pulple-light px-md-4 m-3">get start</button>
					<button class="btn btn-sm btn-rounded btn-yellow px-md-4 m-3">get start</button>
					<button class="btn btn-rounded btn-outline-primary px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-outline-green px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-outline-white px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-outline-pulple-light px-md-5 m-3">get start</button>
					<button class="btn btn-rounded btn-outline-yellow px-md-5 m-3">get start</button>
					<button class="btn btn btn-rounded btn-primary m-3 px-4">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
					<button class="btn btn btn-rounded btn-green m-3 px-4">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
					<button class="btn btn btn-rounded btn-primary m-3 px-md-5">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
					<button class="btn btn btn-rounded btn-green m-3 px-md-5">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
					<button class="btn btn btn-sm btn-rounded btn-primary m-3 px-md-4">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
					<button class="btn btn btn-sm btn-rounded btn-green m-3 px-md-4">
						<i class="fa fa-android mr-1"></i> Play Store
					</button>
				</div>
			</div>
		</div>
	</section>

app/views/pages/Countdown.html.erb
<section class="u-py-100 u-pt-lg-200 u-pb-lg-150 u-flex-center" style="background-image: linear-gradient(to right top,#f1baf3,#c99cd1,#a37fb0,#7f6490,#5d4970);">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center text-white">
          <h1 class="text-white">
            Countdown
          </h1>
          <div class="u-h-4 u-w-50 bg-white rounded mx-auto my-4"></div>
          <p class="lead">
            Meet the amazing team behind this project and find out more
            <br> about how we work.
          </p>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-10 mx-auto">
          <ul data-countdown="2019/01/01" class="list-inline text-center u-ff-dosis">
            <li class="list-inline-item box-shadow-v2 p-5 m-3 rounded">
              <span class="u-fs-36 countdown-days d-block"></span>
              <span>Days</span>
            </li>
            <li class="list-inline-item box-shadow-v2 p-5 m-3 rounded">
              <span class="u-fs-36 countdown-hours d-block"></span>
              <span>Hours</span>
            </li>
            <li class="list-inline-item box-shadow-v2 p-5 m-3 rounded">
              <span class="u-fs-36 countdown-minutes d-block"></span>
              <span>Minutes</span>
            </li>
            <li class="list-inline-item box-shadow-v2 p-5 m-3 rounded">
              <span class="u-fs-36 countdown-seconds d-block"></span>
              <span>Second</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>